FROM node:lts
# FROM arm64v8/debian:bullseye-slim


 RUN apt-get update && apt-get install -y \
     libreoffice \
    fonts-croscore \
    fonts-liberation \
    fonts-dejavu \
    fontconfig \
    fonts-freefont-ttf \
    fonts-noto \
    fonts-roboto \
    # Puppeteer dependencies for Facebook scraping
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get install -y fontconfig
RUN fc-cache -f -v

ENV LIBREOFFICE_PROFILE=/tmp/libreoffice-profile
RUN mkdir -p $LIBREOFFICE_PROFILE && \
    chmod -R 777 $LIBREOFFICE_PROFILE


COPY fonts/fonts.conf /etc/fonts/fonts.conf
# RUN fc-cache -fv && mkdir -p /tmp/fonts-cache && chmod 777 /tmp/fonts-cache

RUN mkdir -p /app/certificates/templates /app/certificates/generated && \
    chown -R node:node /app/certificates

RUN mkdir -p /app/requirements && \
    chown -R node:node /app/requirements

RUN mkdir -p /app/organizations && \ 
    mkdir -p /app/organizations/requirements && \
    chown -R node:node /app/organizations

RUN mkdir -p /app/applications && \
    chown -R node:node /app/applications

WORKDIR /app
COPY package*.json ./

RUN ls -ld /app/certificates && \
    ls -l /app/certificates

RUN npm install 
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]

