import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import jwksClient from 'jwks-rsa';
import 'dotenv/config';
import { can, canAny } from '../services/permissionService';
import { prisma } from '../config/db';

interface JwtUserInfo {
  user_id?: string;
  email: string;
  f_name?: string;
  l_name?: string;
  role?: string;
  program_id?: string | number;
  program_name?: string;
  permissions?: string[];
  organizations?: any[];
  pending_application?: any;
}

interface DecodedToken extends jwt.JwtPayload {
  result?: Array<{ user_info: JwtUserInfo }>;
}

interface AzureJwtPayload extends jwt.JwtPayload {
  preferred_username?: string;
  name?: string;
  sub?: string;
}

// export const authMiddleware = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
//   console.log('DEBUG AUTH: authMiddleware called for:', req.method, req.url);
//   const token = req.headers['authorization']?.split(' ')[1];
//   console.log('DEBUG AUTH: Token:', token ? `${token.substring(0, 20)}...` : 'No token');

//   if (!token) {
//     console.log('DEBUG AUTH: No token provided, returning 401');
//     res.status(401).json({ message: 'No token provided' });
//     return;
//   }

//   jwt.verify(token, process.env.JWT_SECRET as string, (err, decoded) => {
//     if (err) {
//       console.log('DEBUG AUTH: Token verification failed:', err.message);
//       res.status(401).json({ message: 'Invalid token' });
//       return;
//     }

//     const payload = decoded as DecodedToken;
//     const userInfo = payload.result?.[0]?.user_info;

//     if (!userInfo) {
//       console.log('DEBUG AUTH: Invalid token structure, decoded:', decoded);
//       res.status(401).json({ message: 'Invalid token structure' });
//       return;
//     }

//     console.log('DEBUG AUTH: Token verified successfully for user:', userInfo.email);

//     req.user = {
//       user_id: userInfo.user_id ?? userInfo.email,
//       email: userInfo.email,
//       first_name: userInfo.f_name,
//       last_name: userInfo.l_name,
//       role: userInfo.role,
//       program_id: userInfo.program_id,
//       program_name: userInfo.program_name,
//       permissions: userInfo.permissions,
//       organizations: userInfo.organizations,
//       pending_application: userInfo.pending_application,
//     };
//     next();
//   });
// };

export const validateAzureJWT = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const token = req.headers.authorization
      ? req.headers.authorization.split(' ')[1]
      : (req.query.access_token as string);

    if (!token) {
      res.status(401).json({ error: 'Token missing' });
      return;
    }

    const decoded = jwt.decode(token, { complete: true }) as jwt.Jwt | null;

    if (!decoded || !decoded.header || !decoded.header.kid) {
      res.status(401).json({ error: 'Invalid token structure' });
      return;
    }

    const client = jwksClient({
      jwksUri: 'https://login.microsoftonline.com/common/discovery/keys',
    });

    const key = await client.getSigningKey(decoded.header.kid as string);
    const publicKey = key.getPublicKey();

    const verified = jwt.verify(token, publicKey, {
      audience: process.env.AZURE_CLIENT_ID,
      issuer: `https://login.microsoftonline.com/${process.env.AZURE_TENANT_ID}/v2.0`,
    }) as AzureJwtPayload;

    const email = verified.preferred_username;
    if (!email) {
      res.status(401).json({ error: 'Token missing email claim' });
      return;
    }

    // ── 1. Look up user in tbl_user by email ──────────────────────────────
    let dbUser = await prisma.tbl_user.findFirst({
      where: { email },
      select: {
        user_id: true,
        f_name: true,
        l_name: true,
        email: true,
        tbl_role: { select: { role_name: true } },
      },
    });

    // ── 2. First-time login: check tbl_user_application staging ──────────
    if (!dbUser) {
      const staging = await prisma.tbl_user_application.findFirst({
        where: { email, status: 'Approved' },
        include: { tbl_role: { select: { role_id: true, role_name: true } } },
      });

      if (!staging) {
        res.status(403).json({
          error: 'ACCOUNT_NOT_APPROVED',
          message: 'Your account has not been approved yet. Please contact the SDAO.',
        });
        return;
      }

      // Block students before provisioning — mobile app only
      if (staging.tbl_role.role_name === 'Student') {
        res.status(403).json({ error: 'STUDENT_WEB_ACCESS_DENIED' });
        return;
      }

      // Auto-provision: INSERT into tbl_user (UUID generated by DB)
      dbUser = await prisma.tbl_user.create({
        data: {
          email,
          f_name: verified.name?.split(',')[1]?.trim() ?? '',
          l_name: verified.name?.split(',')[0]?.trim() ?? '',
          role_id: staging.role_id,
          program_id: staging.program_id ?? undefined,
          status: 'Active',
        },
        select: {
          user_id: true,
          f_name: true,
          l_name: true,
          email: true,
          tbl_role: { select: { role_name: true } },
        },
      });

      // Mark staging record as transferred
      await prisma.tbl_user_application.update({
        where: { application_id: staging.application_id },
        data: { transferred_at: new Date() },
      });

      console.log(`[Auth] Auto-provisioned new user from staging: ${email} → ${dbUser.user_id}`);
    }

    // ── 3. Block students on web — UNLESS they are an active executive in any org ─
    // Students who hold an executive rank in an org get web access via tbl_rank_permission.
    if (dbUser.tbl_role?.role_name === 'Student') {
      const execMembership = await prisma.tbl_organization_members.findFirst({
        where: {
          user_id: dbUser.user_id,
          member_type: 'Executive',
          status: 'Active',
        },
        select: { member_id: true },
      });

      if (!execMembership) {
        res.status(403).json({ error: 'STUDENT_WEB_ACCESS_DENIED' });
        return;
      }
    }

    req.user = {
      f_name: dbUser.f_name ?? verified.name?.split(',')[1]?.trim(),
      l_name: dbUser.l_name ?? verified.name?.split(',')[0]?.trim(),
      user_id: dbUser.user_id,
      email: dbUser.email,
    };

    next();
  } catch (error: any) {
    console.error('validateAzureJWT error:', error.message);
    res.status(401).json({ error: 'Invalid token' });
  }
};

/**
 * Require ALL of the listed permissions (cache-aware via permissionService).
 * Optionally scope to an org by passing orgIdResolver.
 *
 * Usage:
 *   router.get('/secret', validateAzureJWT, hasPermission('manage_analytics'), handler)
 *   router.get('/org/:id/members', validateAzureJWT, hasPermission('view_org_members', req => Number(req.params.id)), handler)
 */
export const hasPermission = (
  requiredPermissions: string | string[],
  orgIdResolver: ((req: Request) => number | null) | null = null
) =>
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const userId = req.user?.user_id ?? req.user?.email ?? req.userId;
      if (!userId) {
        res.status(401).json({ message: 'Unauthorized' });
        return;
      }

      const orgId = orgIdResolver ? orgIdResolver(req) : null;
      const required = Array.isArray(requiredPermissions) ? requiredPermissions : [requiredPermissions];

      // All listed permissions must be satisfied
      const checks = await Promise.all(required.map((p) => can(userId, p, orgId)));
      const allowed = checks.every(Boolean);

      if (!allowed) {
        res.status(403).json({ error: 'Access denied', required });
        return;
      }

      next();
    } catch (error: any) {
      console.error('Permission check error:', error);
      res.status(500).json({ error: error.message });
    }
  };

/**
 * Require ANY ONE of the listed permissions.
 */
export const hasAnyPermission = (
  requiredPermissions: string[],
  orgIdResolver: ((req: Request) => number | null) | null = null
) =>
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const userId = req.user?.user_id ?? req.user?.email ?? req.userId;
      if (!userId) {
        res.status(401).json({ message: 'Unauthorized' });
        return;
      }

      const orgId = orgIdResolver ? orgIdResolver(req) : null;
      const allowed = await canAny(userId, requiredPermissions, orgId);

      if (!allowed) {
        res.status(403).json({ error: 'Access denied', required: requiredPermissions });
        return;
      }

      next();
    } catch (error: any) {
      console.error('Permission check error:', error);
      res.status(500).json({ error: error.message });
    }
  };

export const requireWebAccess = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const userId = req.user?.user_id ?? req.userId;
    if (!userId) {
      res.status(401).json({ message: 'Unauthorized' });
      return;
    }

    const allowed = await can(userId, 'WEB_ACCESS');
    if (!allowed) {
      res.status(403).json({
        error: 'WEB_ACCESS_DENIED',
        message: 'Your account does not have access to the web application. Please use the mobile app.',
        mobileOnly: true,
      });
      return;
    }

    next();
  } catch (err: any) {
    console.error('[requireWebAccess] error:', err);
    next(err);
  }
};
